FROM openjdk:8-jdk-alpine
MAINTAINER Krishna Murthy P Mirajkar <kpmirajkar@outlook.com>
VOLUME /tmp
EXPOSE 8010
ARG JAR_FILE=target/add-employee-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} add-employee-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/add-employee-0.0.1-SNAPSHOT.jar"]