#mongodb
spring.data.mongodb.uri=mongodb://mongo:27017/testdb
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=app1

#logging
logging.level.org.springframework.data=debug
logging.level.=error
