server:
  port: 8010

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: ADD-EMPLOYEE

logging:
  level:
    org:
      springframework:
        data: debug
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/testdb
